# this file is compiled by nmbl
version: '3.7'

TEMPLATE_CONFIGS

services:
  PROJECT:
    <<: *wp_site
    image: johnrom/docker-wordpress-wp-cli-xdebug:latest
    volumes_from:
      - PROJECT_files
    environment:
      - VIRTUAL_HOST=PROJECT.local
    links:
      - PROJECT_db:mysql

  PROJECT_files:
    <<: *wp_files
    image: johnrom/docker-wordpress-wp-cli-xdebug-soap:latest
    volumes:
      - ${WP_ROOT}:/var/www/html
      - ${SITE}/cachegrind:/tmp/cachegrind
      - ${SITE}/configuration/z-05-php-project.ini:/usr/local/etc/php/conf.d/z-05-php-project.ini

  PROJECT_db:
    <<: *wp_db
    volumes:
      - PROJECT_db_volume:/var/lib/mysql

  PROJECT_pma:
    <<: *wp_pma
    environment:
      - VIRTUAL_HOST=phpmyadmin.PROJECT.local
    links:
      - PROJECT_db:mysql

  PROJECT_webgrind:
    <<: *wp_webgrind
    environment:
      - VIRTUAL_HOST=webgrind.PROJECT.local
    volumes:
      - NIMBLE/sites/PROJECT/cachegrind:/tmp/xdebug
